spring.application.name=data-loader-java

# Database Configuration (Spring Boot will auto-configure a DataSource)
spring.datasource.url=jdbc:postgresql://localhost:5432/electric_vehicle_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

data.loader.csv.filepath=classpath:Electric_Vehicle_Population_Data.csv
data.loader.batch.size=1000

# Logging
logging.level.com.example.evloader=INFO
logging.level.org.springframework.jdbc.core=DEBUG
