---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-api-service
  labels:
    app: ev-api-service
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: ev-api-service
  template:
    metadata:
      labels:
        app: ev-api-service
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "{{.Values.image.repository}}:{{.Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.Values.service.targetPort}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: {{.Values.probes.livenessInitialDelaySeconds | default 60}}
            periodSeconds: {{.Values.probes.periodSeconds | default 10}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds | default 5}}
            failureThreshold: {{.Values.probes.failureThreshold | default 5}}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: {{.Values.probes.readinessInitialDelaySeconds | default 30}}
            periodSeconds: {{.Values.probes.periodSeconds | default 10}}
            timeoutSeconds: {{.Values.probes.timeoutSeconds | default 5}}
            failureThreshold: {{.Values.probes.failureThreshold | default 5}}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{.Release.Name}}-postgresql:5432/{{.Values.postgresql.auth.database}}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{.Values.postgresql.auth.username}}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{.Values.postgresql.auth.password}}"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
              value: "100MB"
            - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
              value: "100MB"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1536m -Xms512m"
          resources:
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
